USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS SNAF_POPULATION_DB;
CREATE SCHEMA IF NOT EXISTS SNAF_POPULATION_DB.DATA_SCHEMA;

CREATE STAGE IF NOT EXISTS SNAF_POPULATION_DB.DATA_SCHEMA.RAW_DATA;

CREATE OR REPLACE TABLE SNAF_POPULATION_DB.DATA_SCHEMA.COUNTRY_POP_BY_YEAR(
    country_name varchar,
    country_code varchar,
    year int,
    value int
);

CREATE OR REPLACE SECURE VIEW SNAF_POPULATION_DB.DATA_SCHEMA.COUNTRY_POP_BY_YEAR_2000 AS SELECT * FROM SNAF_POPULATION_DB.DATA_SCHEMA.COUNTRY_POP_BY_YEAR WHERE YEAR >= 2000;

SELECT * FROM SNAF_POPULATION_DB.DATA_SCHEMA.COUNTRY_POP_BY_YEAR_2000;