
CREATE APPLICATION PACKAGE SNAF_POPULATION_PACKAGE TYPE = DATA;

PUT file://./app/V1/manifest.yml snow://package/SNAF_POPULATION_PACKAGE/versions/live/ OVERWRITE=TRUE AUTO_COMPRESS=FALSE;

ALTER APPLICATION PACKAGE SNAF_POPULATION_PACKAGE RELEASE LIVE VERSION;

