PUT file://./app/V3/manifest.yml snow://package/SNAF_POPULATION_PACKAGE/versions/live/ OVERWRITE=TRUE AUTO_COMPRESS=FALSE;
PUT file://./app/V3/INTRO_NB.ipynb snow://package/SNAF_POPULATION_PACKAGE/versions/live/ OVERWRITE=TRUE AUTO_COMPRESS=FALSE;
PUT file://./app/V3/ANALYST_NB.ipynb snow://package/SNAF_POPULATION_PACKAGE/versions/live/ OVERWRITE=TRUE AUTO_COMPRESS=FALSE;


ALTER APPLICATION PACKAGE SNAF_POPULATION_PACKAGE RELEASE LIVE VERSION;