
ALTER APPLICATION PACKAGE SNAF_POPULATION_PACKAGE ADD LIVE VERSION;

PUT file://./app/V2/manifest.yml snow://package/SNAF_POPULATION_PACKAGE/versions/live/ OVERWRITE=TRUE AUTO_COMPRESS=FALSE;

ALTER APPLICATION PACKAGE SNAF_POPULATION_PACKAGE RELEASE LIVE VERSION;

