
TRUNCATE SNAF_POPULATION_DB.DATA_SCHEMA.COUNTRY_POP_BY_YEAR;
COPY INTO SNAF_POPULATION_DB.DATA_SCHEMA.COUNTRY_POP_BY_YEAR FROM @SNAF_POPULATION_DB.DATA_SCHEMA.RAW_DATA/population.csv
FILE_FORMAT = ( TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"');