USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS naspcs_role;

GRANT ROLE naspcs_role TO ROLE accountadmin;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE naspcs_role;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE naspcs_role;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE naspcs_role;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE naspcs_role;
GRANT CREATE APPLICATION PACKAGE ON ACCOUNT TO ROLE naspcs_role;
GRANT CREATE APPLICATION ON ACCOUNT TO ROLE naspcs_role;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE naspcs_role;
CREATE WAREHOUSE IF NOT EXISTS wh_nap WITH WAREHOUSE_SIZE='XSMALL';
GRANT ALL ON WAREHOUSE wh_nap TO ROLE naspcs_role;

USE ROLE naspcs_role;
CREATE DATABASE IF NOT EXISTS mcp_server_app_v1;
CREATE SCHEMA IF NOT EXISTS mcp_server_app_v1.napp;

-- For Provider-side Testing
USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS nac;
GRANT CREATE APPLICATION ON ACCOUNT TO ROLE nac;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE nac;

-- Create the Image Repository
USE ROLE naspcs_role;
CREATE IMAGE REPOSITORY IF NOT EXISTS mcp_server_app_v1.napp.img_repo;
GRANT USAGE ON DATABASE mcp_server_app_v1 TO ROLE nac;
GRANT USAGE ON SCHEMA mcp_server_app_v1.napp TO ROLE nac;
GRANT READ ON IMAGE REPOSITORY mcp_server_app_v1.napp.img_repo TO ROLE nac;
