# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: native-app-examples

on:
  push:
    branches: [ GITHUB_REF ]
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

permissions:
  contents: read

jobs:          
  build-mailorder:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment-file: mailorder/local_test_env.yml
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup test environment
        uses: conda-incubator/setup-miniconda@v2
        with:
            activate-environment: mailorder-testing
            environment-file: mailorder/local_test_env.yml
      - name: Install dependencies
        run: |
              python -m pip install pytest
      - name: Run tests
        working-directory: mailorder
        run: |
          pytest
        