name: native-app-examples

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

permissions:
  contents: read

jobs:          
  build-mailorder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment-file: local_test_env.yml
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Get changes
        id: changed-files
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
                echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
            else
                echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
            fi
      - name: List changed files
        run: |
            for changed_file in ${{ steps.changed-files.outputs.changed_files }}; do
              DIR="$(dirname "${changed_file}")"        
              echo "{DIR}"
            done
      - name: Setup test environment
        uses: conda-incubator/setup-miniconda@v2
        with:
            environment-file: ${{ matrix.environment-file }}
      - name: Install dependencies
        run: |
              python -m pip install pytest
      - name: Run tests
        run: |
          pytest
        