# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: native-app-examples

on:
  push:
    branches: [ GITHUB_REF ]
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

permissions:
  contents: read

jobs:          
  audit-mailorder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run tests
        uses: conda-incubator/setup-miniconda@v2
        with:
            activate-environment: mailorder-testing
            environment-file: mailorder/local_test_env.yml
            auto-activate-base: false
            run: |
              pytest
        