# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: native-app-examples

on:
  push:
    branches: [ GITHUB_REF ]
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

permissions:
  contents: read

jobs:
  setup-conda-env:
    runs-on: ubuntu-latest
    steps:
      - name: Setup conda environment
        run: |
          conda init zsh
          
  audit-mailorder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup testing environment
        working-directory: mailorder
        run: |
          conda init zsh
          conda env update -f local_test_env.yml
          conda activate mailorder-testing
      - name: Run tests
        working-directory: mailorder
        run: |
          pytest
        